// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK7jS776mxmxZG9Xz4XqyaflsTn3IQjRI',
    appId: '1:578330211860:web:03a94795639342821b9901',
    messagingSenderId: '578330211860',
    projectId: 'interview-flutter-test',
    authDomain: 'interview-flutter-test.firebaseapp.com',
    storageBucket: 'interview-flutter-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDuQ2hUEW65_QfFRmfADw9M4ZY0TiGLqk',
    appId: '1:578330211860:android:7fae60b2f360fb381b9901',
    messagingSenderId: '578330211860',
    projectId: 'interview-flutter-test',
    storageBucket: 'interview-flutter-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrJSjeXAXQwb6LT4244PhQKEnyds2EGmY',
    appId: '1:578330211860:ios:df4a235d023ccf291b9901',
    messagingSenderId: '578330211860',
    projectId: 'interview-flutter-test',
    storageBucket: 'interview-flutter-test.appspot.com',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrJSjeXAXQwb6LT4244PhQKEnyds2EGmY',
    appId: '1:578330211860:ios:df4a235d023ccf291b9901',
    messagingSenderId: '578330211860',
    projectId: 'interview-flutter-test',
    storageBucket: 'interview-flutter-test.appspot.com',
    iosBundleId: 'com.example.flutterTest1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK7jS776mxmxZG9Xz4XqyaflsTn3IQjRI',
    appId: '1:578330211860:web:2d5bcd73a801121b1b9901',
    messagingSenderId: '578330211860',
    projectId: 'interview-flutter-test',
    authDomain: 'interview-flutter-test.firebaseapp.com',
    storageBucket: 'interview-flutter-test.appspot.com',
  );
}
